// Autogenerated jute compiler
// @generated from '/home/bbennett/src/jute/testdata/test.jute'

package test // com/github/gozookeeper/jute/test

import (
	"fmt"

	"github.com/go-zookeeper/jute/lib/go/jute"
)

type Container struct {
	V  []string          // v
	M1 map[string]string // m1
	M2 map[int32]int32   // m2
	B  *Basic            // b
}

func (r *Container) GetV() []string {
	if r != nil && r.V != nil {
		return r.V
	}
	return nil
}

func (r *Container) GetM1() map[string]string {
	if r != nil && r.M1 != nil {
		return r.M1
	}
	return nil
}

func (r *Container) GetM2() map[int32]int32 {
	if r != nil && r.M2 != nil {
		return r.M2
	}
	return nil
}

func (r *Container) GetB() *Basic {
	if r != nil && r.B != nil {
		return r.B
	}
	return nil
}

func (r *Container) Read(dec jute.Decoder) (err error) {
	var size int
	if err = dec.ReadStart(); err != nil {
		return err
	}
	size, err = dec.ReadVectorStart()
	if err != nil {
		return err
	}
	if size < 0 {
		r.V = nil
	} else {
		r.V = make([]string, size)
		for i := 0; i < size; i++ {
			s1, err := dec.ReadString()
			if err != nil {
				return err
			}
			if s1 == nil {
				r.V[i] = ""
			} else {
				r.V[i] = *s1
			}
		}
	}
	if err = dec.ReadVectorEnd(); err != nil {
		return err
	}
	size, err = dec.ReadMapStart()
	if err != nil {
		return err
	}
	r.M1 = make(map[string]string)
	var k1 string
	var v1 string
	for i := 0; i < size; i++ {
		s2, err := dec.ReadString()
		if err != nil {
			return err
		}
		if s2 == nil {
			k1 = ""
		} else {
			k1 = *s2
		}
		s2, err := dec.ReadString()
		if err != nil {
			return err
		}
		if s2 == nil {
			v1 = ""
		} else {
			v1 = *s2
		}
		r.M1[k1] = v1
	}
	if err = dec.ReadMapEnd(); err != nil {
		return err
	}
	size, err = dec.ReadMapStart()
	if err != nil {
		return err
	}
	r.M2 = make(map[int32]int32)
	var k2 int32
	var v2 int32
	for i := 0; i < size; i++ {
		k2, err = dec.ReadInt()
		if err != nil {
			return err
		}
		v2, err = dec.ReadInt()
		if err != nil {
			return err
		}
		r.M2[k2] = v2
	}
	if err = dec.ReadMapEnd(); err != nil {
		return err
	}
	if err = dec.ReadRecord(r.B); err != nil {
		return err
	}
	if err = dec.ReadEnd(); err != nil {
		return err
	}
	return nil
}

func (r *Container) Write(enc jute.Encoder) error {
	if err := enc.WriteStart(); err != nil {
		return err
	}
	if err := enc.WriteVectorStart(len(r.V), r.V == nil); err != nil {
		return err
	}
	for _, v := range r.V {
		if err := enc.WriteString(&v); err != nil {
			return err
		}
	}
	if err := enc.WriteVectorEnd(); err != nil {
		return err
	}
	if err := enc.WriteMapStart(len(r.M1)); err != nil {
		return err
	}
	for k, v := range r.M1 {
		if err := enc.WriteString(&k); err != nil {
			return err
		}
		if err := enc.WriteString(&v); err != nil {
			return err
		}
	}
	if err := enc.WriteMapEnd(); err != nil {
		return err
	}
	if err := enc.WriteMapStart(len(r.M2)); err != nil {
		return err
	}
	for k, v := range r.M2 {
		if err := enc.WriteInt(k); err != nil {
			return err
		}
		if err := enc.WriteInt(v); err != nil {
			return err
		}
	}
	if err := enc.WriteMapEnd(); err != nil {
		return err
	}
	if err := enc.WriteRecord(r.B); err != nil {
		return err
	}
	if err := enc.WriteEnd(); err != nil {
		return err
	}
	return nil
}

func (r *Container) String() string {
	if r == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Container(%+v)", *r)
}
