// Autogenerated jute compiler
// @generated from 'testdata/test.jute'

package test2 // com/github/gozookeeper/jute/test2

import (
	"fmt"

	"github.com/go-zookeeper/jute/lib/go/jute"
)

type Shared struct {
	I int32 // i
}

func (r *Shared) GetI() int32 {
	if r != nil {
		return r.I
	}
	return 0
}

func (r *Shared) Read(dec jute.Decoder) (err error) {
	if err = dec.ReadStart(); err != nil {
		return err
	}
	r.I, err = dec.ReadInt()
	if err != nil {
		return err
	}
	if err = dec.ReadEnd(); err != nil {
		return err
	}
	return nil
}

func (r *Shared) Write(enc jute.Encoder) error {
	if err := enc.WriteStart(); err != nil {
		return err
	}
	if err := enc.WriteInt(r.I); err != nil {
		return err
	}
	if err := enc.WriteEnd(); err != nil {
		return err
	}
	return nil
}

func (r *Shared) String() string {
	if r == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Shared(%+v)", *r)
}
