// Autogenerated jute compiler
// @generated from '/home/pmazzini/repos/jute/testdata/zookeeper.jute'

package txn // github.com/go-zookeeper/zk/internal/txn

import (
	"fmt"

	"github.com/go-zookeeper/jute/lib/go/jute"
)

type CreateSessionTxn struct {
	TimeOut int32 // timeOut
}

func (r *CreateSessionTxn) GetTimeOut() int32 {
	if r != nil {
		return r.TimeOut
	}
	return 0
}

func (r *CreateSessionTxn) Read(dec jute.Decoder) (err error) {
	if err = dec.ReadStart(); err != nil {
		return err
	}
	r.TimeOut, err = dec.ReadInt()
	if err != nil {
		return err
	}
	if err = dec.ReadEnd(); err != nil {
		return err
	}
	return nil
}

func (r *CreateSessionTxn) Write(enc jute.Encoder) error {
	if err := enc.WriteStart(); err != nil {
		return err
	}
	if err := enc.WriteInt(r.TimeOut); err != nil {
		return err
	}
	if err := enc.WriteEnd(); err != nil {
		return err
	}
	return nil
}

func (r *CreateSessionTxn) String() string {
	if r == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateSessionTxn(%+v)", *r)
}
