// Autogenerated jute compiler
// @generated from 'testdata/zookeeper.jute'

package txn // github.com/go-zookeeper/zk/internal/txn

import (
	"fmt"

	"github.com/go-zookeeper/jute/lib/go/jute"
)

type SetMaxChildrenTxn struct {
	Path string // path
	Max  int32  // max
}

func (r *SetMaxChildrenTxn) GetPath() string {
	if r != nil {
		return r.Path
	}
	return ""
}

func (r *SetMaxChildrenTxn) GetMax() int32 {
	if r != nil {
		return r.Max
	}
	return 0
}

func (r *SetMaxChildrenTxn) Read(dec jute.Decoder) (err error) {
	if err = dec.ReadStart(); err != nil {
		return err
	}
	r.Path, err = dec.ReadString()
	if err != nil {
		return err
	}
	r.Max, err = dec.ReadInt()
	if err != nil {
		return err
	}
	if err = dec.ReadEnd(); err != nil {
		return err
	}
	return nil
}

func (r *SetMaxChildrenTxn) Write(enc jute.Encoder) error {
	if err := enc.WriteStart(); err != nil {
		return err
	}
	if err := enc.WriteString(r.Path); err != nil {
		return err
	}
	if err := enc.WriteInt(r.Max); err != nil {
		return err
	}
	if err := enc.WriteEnd(); err != nil {
		return err
	}
	return nil
}

func (r *SetMaxChildrenTxn) String() string {
	if r == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SetMaxChildrenTxn(%+v)", *r)
}
