name: unittest
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unittest:
    name: unittest
    strategy:
      matrix:
        go-version: [1.18, 1.19]
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
            go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test code
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload code coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
